/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snake.game;

public class App {

  public static void main(String[] args) {
    Arena arena = new Arena.Builder().height(25).width(100).tile("*").build();
    System.out.println(arena);
  }

  public String getGreeting() {
    return "Hello World!";
  }
}
